#from .resnet_cifar import *
from .vgg import *
from .resnet_orig import * 
from .densenet import * 
from .googlenet import *
from .inception import * 
from .mobilenet import * 
from .resnet import * 
from .shufflenet import *