from .resnet import *
from .alexnet import *
from .shufflenetv2 import *
#from .classifier import *
from .vgg import *
from .inception import *
#from .resnet_cifar import *
from .squeezenet import *
from .mobilenet import *